# Generated by Django 2.2.3 on 2019-07-16 06:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Famale')], null=True)),
                ('mobile', models.CharField(max_length=20, null=True, unique=True)),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('speciality', models.CharField(max_length=30, null=True)),
                ('salary', models.FloatField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat')], max_length=27)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('cost', models.FloatField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
