# Generated by Django 2.2.3 on 2019-08-04 12:25

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignservice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('grandtotal', models.FloatField(null=True)),
                ('delivery_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Famale')], null=True)),
                ('mobile', models.CharField(max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('speciality', models.CharField(max_length=30, null=True)),
                ('salary', models.FloatField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat')], max_length=27)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('cost', models.FloatField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignservice_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Assignservice')),
            ],
        ),
        migrations.AddField(
            model_name='assignservice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Customer'),
        ),
        migrations.AddField(
            model_name='assignservice',
            name='fuller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Fuller'),
        ),
    ]
