# Generated by Django 2.2.3 on 2019-08-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignservice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('delivery_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Assignservice_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Assignservice')),
            ],
        ),
        migrations.AddField(
            model_name='assignservice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Customer'),
        ),
        migrations.AddField(
            model_name='assignservice',
            name='fuller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Fuller'),
        ),
    ]
