# Generated by Django 2.2.3 on 2019-07-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Cost',
            new_name='cost',
        ),
    ]
