# Generated by Django 2.2.3 on 2019-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignservice_detail',
            name='service',
            field=models.IntegerField(null=True),
        ),
    ]
