# Generated by Django 2.2.3 on 2019-08-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190801_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignservice',
            name='grandtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
