# Generated by Django 2.2.3 on 2019-07-16 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_assignservice_assignservice_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignservice',
            name='amount',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignservice',
            name='discount',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
