# Generated by Django 2.2.3 on 2019-08-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_assignservice_detail_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignservice_detail',
            old_name='service',
            new_name='service_id',
        ),
    ]
