# Generated by Django 2.2.3 on 2019-08-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_assignservice_grandtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignservice',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assignservice',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assignservice',
            name='grandtotal',
            field=models.FloatField(null=True),
        ),
    ]
