# Generated by Django 2.2.3 on 2019-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190715_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('Age', models.IntegerField()),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Famale')], null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
