# Generated by Django 2.2.3 on 2019-07-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190716_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignservice_details',
            new_name='Assignservice_detail',
        ),
    ]
