# Generated by Django 2.2.3 on 2019-08-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190806_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignservice_detail',
            name='service',
            field=models.IntegerField(null=True),
        ),
    ]
