# Generated by Django 2.2.3 on 2019-07-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190731_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignservice',
            old_name='assign_date',
            new_name='delivery_date',
        ),
    ]
