# Generated by Django 2.2.3 on 2019-07-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190715_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Age',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
