# Generated by Django 2.2.3 on 2019-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190715_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('speciality', models.CharField(max_length=30, null=True)),
                ('salary', models.FloatField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('sun', models.BooleanField()),
                ('mon', models.BooleanField()),
                ('tue', models.BooleanField()),
                ('wed', models.BooleanField()),
                ('thu', models.BooleanField()),
                ('fri', models.BooleanField()),
                ('sat', models.BooleanField()),
            ],
        ),
    ]
