# Generated by Django 2.2.3 on 2019-08-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190806_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignservice_detail',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Assignservice'),
        ),
        migrations.AlterField(
            model_name='assignservice_detail',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
    ]
