# Generated by Django 2.2.3 on 2019-07-15 12:13

from django.db import migrations
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_fuller_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuller',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='fuller',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='fuller',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='fuller',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='fuller',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='fuller',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='fuller',
            name='wed',
        ),
        migrations.AddField(
            model_name='fuller',
            name='Days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat')], default=django.utils.timezone.now, max_length=27),
            preserve_default=False,
        ),
    ]
