# Generated by Django 2.2.3 on 2019-08-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20190806_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignservice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignservice',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignservice',
            name='grandtotal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignservice',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
