# Generated by Django 2.2.3 on 2019-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190806_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
