# Generated by Django 2.2.3 on 2019-07-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190715_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuller',
            old_name='Days',
            new_name='days',
        ),
    ]
