# Generated by Django 2.2.3 on 2019-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20190806_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
